name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    uses: TYPO3-Documentation/.github/.github/workflows/reusable-backport.yml@e2ccd27accf9ee90f8eca7e037a12fabe089b51b
    with:
      label_pattern: "^backport (.+)$"
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
