name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    uses: TYPO3-Documentation/.github/.github/workflows/reusable-backport.yml@48e225fb2124ac073aa08de0b78b50ab51fec3f9
    with:
      label-pattern: "backport *"
